env:
  browser: true
extends: "airbnb"
parser: "babel-eslint"
rules:
  react/jsx-filename-extension:
    - "error"
    -
      "extensions":
        - ".js"
        - ".jsx"
  semi:
    - "error"
    - "never"
