env:
  browser: true
extends:
  - "airbnb"
  - "plugin:import/errors"
  - "plugin:import/warnings"
parser: "babel-eslint"
rules:
  react/jsx-filename-extension:
    - "error"
    -
      "extensions":
        - ".js"
        - ".jsx"
  semi:
    - "error"
    - "never"
